# Generated by Django 4.1.13 on 2024-09-02 08:58

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('post_title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('image_link', models.URLField(max_length=255)),
                ('author_name', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('content_paragraphs', djongo.models.fields.JSONField()),
            ],
        ),
    ]
